// <auto-generated />
using System;
using Aviator.Main.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aviator.Main.Migrations
{
    [DbContext(typeof(AviatorContext))]
    [Migration("20240113144453_AddedSeed")]
    partial class AddedSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Aviator.Main.Models.Endpoint", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Decoder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Outputs");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("74ec7f80-000c-4c23-b42f-5512dc9a21ff"),
                            Address = "feed.airframes.io",
                            Decoder = 0,
                            Port = 5552,
                            Protocol = 1
                        },
                        new
                        {
                            Guid = new Guid("78f40023-5ddf-480e-aae9-a0c8e1a4ff2e"),
                            Address = "feed.airframes.io",
                            Decoder = 1,
                            Port = 5556,
                            Protocol = 0
                        },
                        new
                        {
                            Guid = new Guid("53703d00-aba1-4d0b-b7c5-50dbea253659"),
                            Address = "feed.airframes.io",
                            Decoder = 4,
                            Port = 5550,
                            Protocol = 1
                        },
                        new
                        {
                            Guid = new Guid("a456e7d4-6101-4b6d-8193-126058188b07"),
                            Address = "feed.airframes.io",
                            Decoder = 2,
                            Port = 5571,
                            Protocol = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
