// <auto-generated />
using System;
using Aviator.Main.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aviator.Main.Migrations
{
    [DbContext(typeof(AviatorContext))]
    [Migration("20240115185752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Aviator.Main.Models.Endpoint", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Decoder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Endpoints");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4c6518dd-ac1d-4347-9beb-6e3310c11701"),
                            Address = "feed.airframes.io",
                            Decoder = 0,
                            Port = 5552,
                            Protocol = 1
                        },
                        new
                        {
                            Guid = new Guid("df456bcb-c580-4409-884f-20d517ad6925"),
                            Address = "feed.airframes.io",
                            Decoder = 1,
                            Port = 5556,
                            Protocol = 0
                        },
                        new
                        {
                            Guid = new Guid("3ab42391-2fd9-4930-9351-a5c2481a52c5"),
                            Address = "feed.airframes.io",
                            Decoder = 4,
                            Port = 5550,
                            Protocol = 1
                        },
                        new
                        {
                            Guid = new Guid("ce773214-564d-48b3-b345-b726cbe7d10d"),
                            Address = "feed.airframes.io",
                            Decoder = 2,
                            Port = 5571,
                            Protocol = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
